import {
  Document,
  Page,
  Text,
  View,
  StyleSheet
} from "@react-pdf/renderer";
import { formatGBP, formatDate } from "@/lib/utils/formatters";

type InvoicePdfProps = {
  invoice: {
    invoice_number: string;
    issue_date: string;
    due_date: string;
    payment_terms_days: number;
    balance_due: number;
    subtotal: number;
    total: number;
    notes: string | null;
    created_at: string;
    landlords?: {
      name: string;
      billing_address?: string | null;
      email?: string | null;
    } | null;
    billing_profiles?: {
      sender_company_name: string;
      sender_address?: string | null;
      bank_account_holder_name: string;
      bank_account_number: string;
      bank_sort_code: string;
      footer_thank_you_text: string;
    } | null;
    created_by?: { display_name: string | null } | null;
  };
  items: Array<{
    description: string;
    quantity: number;
    rate: number;
    amount: number;
  }>;
};

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1C2A39"
  },
  header: {
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 4
  },
  subheader: {
    fontSize: 10,
    marginBottom: 12
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between"
  },
  block: {
    marginBottom: 16
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 8
  },
  label: {
    fontSize: 9,
    color: "#2F3A4A"
  },
  value: {
    fontSize: 10,
    marginTop: 2
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    paddingBottom: 6,
    marginBottom: 6
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4
  },
  colItem: { width: "52%" },
  colQty: { width: "12%", textAlign: "right" },
  colRate: { width: "18%", textAlign: "right" },
  colAmount: { width: "18%", textAlign: "right" },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8
  },
  totalsLabel: { width: "20%", textAlign: "right", fontSize: 9 },
  totalsValue: { width: "18%", textAlign: "right", fontSize: 10 },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    marginVertical: 10
  },
  footer: {
    marginTop: 12,
    fontSize: 9
  }
});

export function InvoicePdf({ invoice, items }: InvoicePdfProps) {
  const sender = invoice.billing_profiles;
  const receiver = invoice.landlords;
  const generatedBy = invoice.created_by?.display_name ?? "Agent";
  const generatedAt = new Date().toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.block}>
          <Text style={styles.header}>{sender?.sender_company_name ?? ""}</Text>
          <Text style={styles.subheader}>Business Banking</Text>
          <View>
            <Text style={styles.label}>Account holder name: {sender?.bank_account_holder_name ?? ""}</Text>
            <Text style={styles.label}>Account number: {sender?.bank_account_number ?? ""}</Text>
            <Text style={styles.label}>Sort code: {sender?.bank_sort_code ?? ""}</Text>
          </View>
        </View>

        <View style={[styles.block, styles.row]}>
          <View>
            <Text style={styles.title}>INVOICE</Text>
            <Text style={styles.value}># {invoice.invoice_number}</Text>
          </View>
          <View>
            <Text style={styles.label}>Date: {formatDate(invoice.issue_date)}</Text>
            <Text style={styles.label}>Payment Terms: {invoice.payment_terms_days} days</Text>
            <Text style={styles.label}>Due Date: {formatDate(invoice.due_date)}</Text>
            <Text style={styles.label}>Balance Due: {formatGBP(Number(invoice.balance_due))}</Text>
          </View>
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>RECEIVER'S DETAILS:</Text>
          <Text style={styles.value}>{receiver?.name ?? ""}</Text>
          {receiver?.billing_address ? (
            <Text style={styles.value}>{receiver.billing_address}</Text>
          ) : null}
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>GENERATED BY:</Text>
          <Text style={styles.value}>{generatedBy}</Text>
        </View>

        <View style={styles.tableHeader}>
          <Text style={styles.colItem}>Item</Text>
          <Text style={styles.colQty}>Quantity</Text>
          <Text style={styles.colRate}>Rate</Text>
          <Text style={styles.colAmount}>Amount</Text>
        </View>
        {items.map((item, index) => (
          <View key={`item-${index}`} style={styles.tableRow}>
            <Text style={styles.colItem}>{item.description}</Text>
            <Text style={styles.colQty}>{item.quantity}</Text>
            <Text style={styles.colRate}>{formatGBP(item.rate)}</Text>
            <Text style={styles.colAmount}>{formatGBP(item.amount)}</Text>
          </View>
        ))}

        <View style={styles.divider} />

        <View style={styles.totalsRow}>
          <Text style={styles.totalsLabel}>Subtotal</Text>
          <Text style={styles.totalsValue}>{formatGBP(Number(invoice.subtotal))}</Text>
        </View>
        <View style={styles.totalsRow}>
          <Text style={styles.totalsLabel}>Total</Text>
          <Text style={styles.totalsValue}>{formatGBP(Number(invoice.total))}</Text>
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>Notes</Text>
          <Text style={styles.value}>{invoice.notes ?? ""}</Text>
        </View>

        <View style={styles.footer}>
          <Text>{sender?.footer_thank_you_text ?? "Thank you for your business!"}</Text>
          <Text>Generated on {generatedAt}</Text>
        </View>
      </Page>
    </Document>
  );
}
