/**
 * Metered usage: what gets counted, what is included, what overage costs.
 *
 * Same convention as the integration catalogue and the envelope packs — the
 * catalogue is code, the database holds only what was consumed. A meter's rate
 * and allowance are frozen onto the counter row at rollup, so changing a number
 * here re-prices only months measured afterwards.
 *
 * Dependency-free on purpose: no `server-only`, no database client, so it loads
 * under `node --test` and can be imported from a client component to render an
 * agency's own usage. Matches `packs.ts` and `rates.ts`.
 *
 * ADDING A METER
 *   1. Add the entry here.
 *   2. Add its count query to `countMeter` in src/lib/cron/usageRollup.ts.
 *   3. That is all — rollup, invoicing and the admin views are driven from this
 *      list.
 */

export type MeterKey =
  | "emails_sent"
  | "ai_messages"
  | "deposits_registered"
  | "sms_sent";

export type Meter = {
  key: MeterKey;
  name: string;
  /** Singular unit, for "1,204 emails". */
  unit: string;
  /** One line explaining exactly what is counted — shown to the agency. */
  description: string;
  /** Included each month before overage applies. */
  includedPerMonth: number;
  /**
   * Pence per unit beyond the allowance.
   *
   * ZERO FOR EVERY METER IN V1, and that is the point rather than an omission.
   * Counting usage and charging for it are separate decisions: this ships the
   * measurement so there is data to price against, while a zero rate produces
   * no invoice line at all — nothing an agency sees or pays changes until a
   * real number is set here. `VAT_RATE_BPS` in rates.ts works the same way.
   */
  overagePencePerUnit: number;
};

export const METERS: Meter[] = [
  {
    key: "emails_sent",
    name: "Emails sent",
    unit: "email",
    description:
      "Emails successfully delivered to tenants, landlords and contractors. Failed sends are not counted.",
    includedPerMonth: 2000,
    overagePencePerUnit: 0,
  },
  {
    key: "ai_messages",
    name: "AI assistant replies",
    unit: "reply",
    description:
      "Replies generated by the AI assistant. Your own messages to it are not counted.",
    includedPerMonth: 500,
    overagePencePerUnit: 0,
  },
  {
    key: "deposits_registered",
    name: "Deposits registered",
    unit: "deposit",
    description:
      "Deposits submitted to mydeposits, TDS or DPS. Drafts that were never submitted are not counted.",
    includedPerMonth: 100,
    overagePencePerUnit: 0,
  },
  {
    key: "sms_sent",
    name: "SMS sent",
    unit: "message",
    description: "Text messages successfully delivered.",
    includedPerMonth: 0,
    overagePencePerUnit: 0,
  },
];

const BY_KEY = new Map(METERS.map((meter) => [meter.key, meter]));

export function getMeter(key: string): Meter | null {
  return BY_KEY.get(key as MeterKey) ?? null;
}

export function isMeterKey(value: string): value is MeterKey {
  return BY_KEY.has(value as MeterKey);
}

export type MeterUsage = {
  meterKey: MeterKey;
  quantity: number;
  included: number;
  billable: number;
  unitPricePence: number;
  amountPence: number;
};

/**
 * Price one meter's consumption for a month.
 *
 * Overage is charged on whole units above the allowance. The allowance and rate
 * are taken from the meter at the moment this is called and then frozen onto
 * the counter row by the caller — this function never reads them again.
 */
export function priceUsage(meter: Meter, quantity: number): MeterUsage {
  const safeQuantity = Math.max(0, Math.trunc(quantity));
  const billable = Math.max(0, safeQuantity - meter.includedPerMonth);

  return {
    meterKey: meter.key,
    quantity: safeQuantity,
    included: meter.includedPerMonth,
    billable,
    unitPricePence: meter.overagePencePerUnit,
    // Integer pence throughout: unit price is already an integer and billable
    // is a whole count, so this cannot accumulate a fractional penny.
    amountPence: billable * meter.overagePencePerUnit,
  };
}

/** "1,204 emails" — pluralised, thousands-separated. */
export function formatUsage(meter: Meter, quantity: number): string {
  const plural = quantity === 1 ? meter.unit : `${meter.unit}s`;
  return `${quantity.toLocaleString("en-GB")} ${plural}`;
}
